defaults:
  - model: lcnn_model
  - writer: wandb
  - metrics: eer
  - datasets: asv
  - dataloader: asv
  - transforms: asv
  - _self_

optimizer:
  _target_: torch.optim.Adam
  betas: [0.9, 0.999]
  lr: 10e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}

loss_function:
  _target_: src.loss.asv.CrossEntropyLoss

trainer:
  log_step: 50
  n_epochs: 20
  epoch_len: 500
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: True
  monitor: "min test_EER"
  save_period: 1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
