defaults:
  - model: lcnn_model
  - writer: wandb
  - metrics: eer
  - datasets: asv
  - dataloader: asv
  - transforms: asv
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "students_solutions/nntumakov.csv" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
